import { EXPANDED_QUESTIONS } from "./expanded-questions";
import { adaptQuestionsForPublicSchool } from "./public-school-adjustments";

export type Question = {
  id: number;
  category: string;
  level: "Fácil" | "Intermediária" | "Difícil";
  prompt: string;
  options: [string, string, string, string];
  answer: number;
  explanation: string;
};

type LegacyQuestion = Omit<Question, "level"> & { level: "Médio" | "Técnico" };

const LEGACY_QUESTIONS: LegacyQuestion[] = [
  {
    id: 1,
    category: "Materiais",
    level: "Médio",
    prompt: "Quais são os componentes básicos do concreto convencional?",
    options: ["Cimento, água, areia e brita", "Cal, gesso, areia e água", "Aço, cimento e argila", "Brita, madeira e cal"],
    answer: 0,
    explanation: "O concreto combina cimento, água, agregado miúdo (areia) e agregado graúdo (brita).",
  },
  {
    id: 2,
    category: "Materiais",
    level: "Técnico",
    prompt: "O ensaio de abatimento do tronco de cone (slump test) avalia principalmente o quê?",
    options: ["A resistência final", "A trabalhabilidade do concreto fresco", "A corrosão do aço", "A massa do cimento"],
    answer: 1,
    explanation: "O slump test verifica a consistência e a trabalhabilidade do concreto ainda fresco.",
  },
  {
    id: 3,
    category: "Materiais",
    level: "Médio",
    prompt: "Por que a cura do concreto é importante?",
    options: ["Para acelerar a ferrugem", "Para manter a umidade e favorecer a resistência", "Para substituir o adensamento", "Para retirar o cimento excedente"],
    answer: 1,
    explanation: "A cura reduz a perda precoce de água e permite que a hidratação do cimento continue adequadamente.",
  },
  {
    id: 4,
    category: "Materiais",
    level: "Técnico",
    prompt: "Em geral, o excesso de água na mistura do concreto tende a:",
    options: ["Aumentar sempre a resistência", "Reduzir a porosidade", "Diminuir a resistência e aumentar a porosidade", "Eliminar a necessidade de cura"],
    answer: 2,
    explanation: "Água em excesso aumenta os vazios após a secagem e costuma reduzir a resistência e a durabilidade.",
  },
  {
    id: 5,
    category: "Materiais",
    level: "Médio",
    prompt: "Qual é uma aplicação comum da argamassa em uma obra?",
    options: ["Armar pilares", "Assentar blocos e revestir paredes", "Substituir toda a fundação", "Fabricar cabos elétricos"],
    answer: 1,
    explanation: "Argamassas são muito usadas no assentamento de blocos e em revestimentos como emboço e reboco.",
  },
  {
    id: 6,
    category: "Materiais",
    level: "Médio",
    prompt: "Como os sacos de cimento devem ser armazenados no canteiro?",
    options: ["Diretamente sobre o solo", "Expostos à chuva", "Em local seco, coberto e sobre estrado", "Misturados com areia úmida"],
    answer: 2,
    explanation: "O cimento deve ficar protegido da umidade e afastado do piso para não empedrar nem perder qualidade.",
  },
  {
    id: 7,
    category: "Materiais",
    level: "Técnico",
    prompt: "No concreto armado, para que serve o cobrimento da armadura?",
    options: ["Apenas para aumentar o peso", "Para proteger o aço e garantir aderência", "Para substituir os estribos", "Para dispensar as formas"],
    answer: 1,
    explanation: "O cobrimento ajuda a proteger a armadura contra corrosão e fogo, além de contribuir para a aderência.",
  },
  {
    id: 8,
    category: "Estruturas",
    level: "Médio",
    prompt: "Por que concreto e aço trabalham bem juntos no concreto armado?",
    options: ["O aço resiste bem à tração e o concreto à compressão", "Ambos são feitos de madeira", "O aço elimina todas as cargas", "O concreto impede qualquer deformação"],
    answer: 0,
    explanation: "Os materiais se complementam: o concreto é eficiente à compressão e o aço, à tração.",
  },
  {
    id: 9,
    category: "Materiais",
    level: "Médio",
    prompt: "Qual destes materiais é um agregado graúdo?",
    options: ["Cimento", "Areia fina", "Brita", "Cal hidratada"],
    answer: 2,
    explanation: "A brita é o agregado graúdo mais comum do concreto; a areia é o agregado miúdo.",
  },
  {
    id: 10,
    category: "Normas",
    level: "Médio",
    prompt: "No Brasil, qual instituição publica grande parte das normas técnicas usadas na construção?",
    options: ["ABNT", "IBGE", "INSS", "BACEN"],
    answer: 0,
    explanation: "A Associação Brasileira de Normas Técnicas (ABNT) publica normas aplicadas a projetos, materiais e execução.",
  },
  {
    id: 11,
    category: "Projetos",
    level: "Técnico",
    prompt: "Em um desenho na escala 1:50, 1 cm no papel representa quanto na realidade?",
    options: ["5 cm", "50 cm", "5 m", "50 m"],
    answer: 1,
    explanation: "Na escala 1:50, cada unidade desenhada corresponde a 50 unidades reais: 1 cm equivale a 50 cm.",
  },
  {
    id: 12,
    category: "Execução",
    level: "Médio",
    prompt: "Qual instrumento simples verifica se uma superfície está horizontal?",
    options: ["Prumo", "Nível de bolha", "Trena", "Esquadro"],
    answer: 1,
    explanation: "O nível de bolha permite conferir a horizontalidade e, em alguns modelos, a verticalidade.",
  },
  {
    id: 13,
    category: "Execução",
    level: "Médio",
    prompt: "O prumo é utilizado principalmente para verificar:",
    options: ["A verticalidade", "A temperatura", "O volume do concreto", "A resistência do solo"],
    answer: 0,
    explanation: "O prumo indica a direção vertical e ajuda a evitar paredes e elementos inclinados.",
  },
  {
    id: 14,
    category: "Execução",
    level: "Médio",
    prompt: "Qual ferramenta ajuda a conferir um ângulo de 90°?",
    options: ["Marreta", "Esquadro", "Desempenadeira", "Talhadeira"],
    answer: 1,
    explanation: "O esquadro é a ferramenta básica para verificar ângulos retos.",
  },
  {
    id: 15,
    category: "Fundações",
    level: "Médio",
    prompt: "Qual é a principal função de uma fundação?",
    options: ["Decorar a fachada", "Transmitir as cargas da construção ao solo", "Conduzir água potável", "Ventilar os ambientes"],
    answer: 1,
    explanation: "A fundação recebe as cargas da estrutura e as transmite ao terreno de forma segura.",
  },
  {
    id: 16,
    category: "Fundações",
    level: "Técnico",
    prompt: "Qual destes é um exemplo de fundação superficial?",
    options: ["Estaca hélice contínua", "Tubulão", "Sapata isolada", "Estaca raiz"],
    answer: 2,
    explanation: "A sapata isolada é uma fundação superficial; estacas e tubulões são fundações profundas.",
  },
  {
    id: 17,
    category: "Geotecnia",
    level: "Técnico",
    prompt: "A sondagem SPT é usada para obter informações principalmente sobre:",
    options: ["A pintura da fachada", "As camadas e a resistência do solo", "A rede elétrica", "A acústica dos ambientes"],
    answer: 1,
    explanation: "A sondagem SPT investiga o perfil do terreno e fornece dados para a escolha e o projeto das fundações.",
  },
  {
    id: 18,
    category: "Estruturas",
    level: "Médio",
    prompt: "Em uma estrutura convencional, a viga normalmente recebe cargas das lajes e as leva para:",
    options: ["As janelas", "Os pilares", "As telhas", "Os rodapés"],
    answer: 1,
    explanation: "As vigas transferem esforços principalmente para os pilares, que os conduzem às fundações.",
  },
  {
    id: 19,
    category: "Estruturas",
    level: "Médio",
    prompt: "Qual elemento estrutural é geralmente vertical e transmite cargas às fundações?",
    options: ["Pilar", "Laje", "Telha", "Contrapiso"],
    answer: 0,
    explanation: "O pilar é um elemento predominantemente vertical que recebe cargas e as conduz para a fundação.",
  },
  {
    id: 20,
    category: "Estruturas",
    level: "Médio",
    prompt: "Qual elemento forma pisos e coberturas planas e distribui cargas para vigas ou pilares?",
    options: ["Laje", "Rodapé", "Vergalhão", "Ralo"],
    answer: 0,
    explanation: "A laje funciona como elemento de superfície, recebendo e distribuindo cargas.",
  },
  {
    id: 21,
    category: "Estruturas",
    level: "Técnico",
    prompt: "O peso próprio de uma estrutura é classificado como:",
    options: ["Carga permanente", "Carga acidental apenas", "Carga inexistente", "Pressão hidráulica"],
    answer: 0,
    explanation: "O peso próprio permanece durante a vida da estrutura e é considerado uma ação permanente.",
  },
  {
    id: 22,
    category: "Estruturas",
    level: "Médio",
    prompt: "Quando um elemento é apertado por forças opostas, ele está principalmente sob:",
    options: ["Tração", "Compressão", "Torção nula", "Flutuação"],
    answer: 1,
    explanation: "Forças que empurram o elemento uma contra a outra produzem compressão.",
  },
  {
    id: 23,
    category: "Estruturas",
    level: "Técnico",
    prompt: "Em uma viga de concreto armado simplesmente apoiada, o aço principal costuma combater principalmente:",
    options: ["Esforços de tração", "Evaporação da água", "Ruído", "Dilatação do vidro"],
    answer: 0,
    explanation: "Na região tracionada da viga, a armadura longitudinal assume esforços que o concreto resiste mal.",
  },
  {
    id: 24,
    category: "Alvenaria",
    level: "Médio",
    prompt: "Na alvenaria de vedação, a parede tem como função principal:",
    options: ["Substituir sempre os pilares", "Fechar e dividir ambientes", "Servir como fundação profunda", "Gerar energia elétrica"],
    answer: 1,
    explanation: "A alvenaria de vedação fecha e separa espaços, sem ser o sistema estrutural principal.",
  },
  {
    id: 25,
    category: "Alvenaria",
    level: "Técnico",
    prompt: "A verga instalada acima de portas e janelas ajuda a:",
    options: ["Distribuir cargas e reduzir fissuras", "Impermeabilizar o telhado", "Medir o terreno", "Aumentar a pressão da água"],
    answer: 0,
    explanation: "A verga vence o vão e redistribui esforços, reduzindo o risco de fissuras nos cantos da abertura.",
  },
  {
    id: 26,
    category: "Segurança",
    level: "Médio",
    prompt: "Qual equipamento protege diretamente a cabeça do trabalhador?",
    options: ["Capacete de segurança", "Rodapé", "Guarda-corpo", "Cone de sinalização"],
    answer: 0,
    explanation: "O capacete é um EPI destinado à proteção da cabeça contra impactos e queda de objetos.",
  },
  {
    id: 27,
    category: "Segurança",
    level: "Técnico",
    prompt: "Qual destes é um exemplo de equipamento de proteção coletiva (EPC)?",
    options: ["Luva individual", "Óculos de proteção", "Guarda-corpo", "Botina"],
    answer: 2,
    explanation: "O guarda-corpo protege coletivamente quem circula próximo a bordas e desníveis.",
  },
  {
    id: 28,
    category: "Segurança",
    level: "Técnico",
    prompt: "Qual norma regulamentadora trata especificamente da segurança na indústria da construção?",
    options: ["NR 6", "NR 10", "NR 18", "NR 35 apenas"],
    answer: 2,
    explanation: "A NR 18 estabelece diretrizes de segurança e saúde no trabalho na indústria da construção.",
  },
  {
    id: 29,
    category: "Segurança",
    level: "Técnico",
    prompt: "A NR 35 está diretamente relacionada a atividades:",
    options: ["Em trabalho em altura", "De desenho arquitetônico", "De dosagem do concreto", "De compra de materiais"],
    answer: 0,
    explanation: "A NR 35 define requisitos para planejamento, organização e execução de trabalho em altura.",
  },
  {
    id: 30,
    category: "Segurança",
    level: "Médio",
    prompt: "Manter o canteiro limpo e com rotas desobstruídas contribui para:",
    options: ["Aumentar tropeços", "Reduzir acidentes e melhorar o fluxo", "Eliminar o uso de EPI", "Dispensar sinalização"],
    answer: 1,
    explanation: "Organização e limpeza reduzem riscos de queda, colisão e perda de produtividade.",
  },
  {
    id: 31,
    category: "Segurança",
    level: "Médio",
    prompt: "Ao usar uma escada portátil, uma conduta segura é:",
    options: ["Apoiá-la em piso instável", "Usar o último degrau como plataforma", "Verificar apoio e estabilidade antes do uso", "Subir carregando objetos pesados nas duas mãos"],
    answer: 2,
    explanation: "O apoio firme e a estabilidade devem ser verificados antes da subida.",
  },
  {
    id: 32,
    category: "Segurança",
    level: "Médio",
    prompt: "Antes de uma intervenção em instalação elétrica, deve-se prioritariamente:",
    options: ["Molhar o local", "Desenergizar e impedir reenergização indevida", "Retirar toda a sinalização", "Usar ferramentas metálicas improvisadas"],
    answer: 1,
    explanation: "A desenergização controlada é uma medida essencial para reduzir o risco de choque elétrico.",
  },
  {
    id: 33,
    category: "Segurança",
    level: "Médio",
    prompt: "Ao identificar uma área com risco no canteiro, o correto é:",
    options: ["Ignorar se o serviço for rápido", "Sinalizar, isolar quando necessário e comunicar", "Apagar os avisos", "Permitir acesso irrestrito"],
    answer: 1,
    explanation: "Sinalização, isolamento e comunicação ajudam a controlar o risco antes da continuidade do trabalho.",
  },
  {
    id: 34,
    category: "Instalações",
    level: "Médio",
    prompt: "Qual é a função do sifão em uma instalação de esgoto?",
    options: ["Aumentar a tensão elétrica", "Criar um fecho hídrico contra gases", "Aquecer a tubulação", "Medir a vazão de concreto"],
    answer: 1,
    explanation: "A água retida no sifão forma um fecho hídrico que dificulta a passagem de gases do esgoto.",
  },
  {
    id: 35,
    category: "Instalações",
    level: "Técnico",
    prompt: "Por que tubulações horizontais de esgoto precisam de declividade adequada?",
    options: ["Para favorecer o escoamento por gravidade", "Para aumentar a pressão elétrica", "Para dispensar conexões", "Para impedir qualquer ventilação"],
    answer: 0,
    explanation: "A declividade permite que efluentes e sólidos escoem pela ação da gravidade.",
  },
  {
    id: 36,
    category: "Instalações",
    level: "Médio",
    prompt: "A água potável deve ser protegida de contato com:",
    options: ["Reservatório limpo", "Redes de esgoto e fontes de contaminação", "Tubulação adequada", "Pontos de consumo"],
    answer: 1,
    explanation: "Separação e proteção das redes evitam contaminação da água destinada ao consumo.",
  },
  {
    id: 37,
    category: "Saneamento",
    level: "Médio",
    prompt: "O tratamento de esgoto contribui principalmente para:",
    options: ["Aumentar a poluição dos rios", "Proteger a saúde e o ambiente", "Eliminar a necessidade de água", "Substituir o projeto estrutural"],
    answer: 1,
    explanation: "Tratar o esgoto reduz contaminantes antes do lançamento ou reúso, protegendo pessoas e ecossistemas.",
  },
  {
    id: 38,
    category: "Sustentabilidade",
    level: "Médio",
    prompt: "Uma utilização possível da água da chuva, após projeto e cuidados adequados, é:",
    options: ["Consumo direto sem tratamento", "Usos não potáveis, como irrigação", "Mistura automática com esgoto", "Injeção em tomadas elétricas"],
    answer: 1,
    explanation: "A água pluvial pode atender usos não potáveis previstos em projeto, reduzindo o consumo de água tratada.",
  },
  {
    id: 39,
    category: "Impermeabilização",
    level: "Médio",
    prompt: "A impermeabilização tem como objetivo principal:",
    options: ["Impedir ou controlar a passagem indesejada de água", "Aumentar vãos estruturais", "Substituir a pintura", "Medir ângulos"],
    answer: 0,
    explanation: "Sistemas impermeabilizantes protegem elementos e ambientes contra infiltrações e umidade.",
  },
  {
    id: 40,
    category: "Coberturas",
    level: "Técnico",
    prompt: "Em encontros do telhado com paredes, o rufo ajuda a:",
    options: ["Evitar entrada de água", "Sustentar sozinho toda a edificação", "Medir o terreno", "Produzir concreto"],
    answer: 0,
    explanation: "Rufos vedam encontros e direcionam a água, reduzindo infiltrações.",
  },
  {
    id: 41,
    category: "Conforto",
    level: "Médio",
    prompt: "A ventilação cruzada ocorre quando:",
    options: ["O ambiente não possui aberturas", "O ar entra e sai por aberturas adequadamente posicionadas", "Todas as portas são vedadas", "O telhado é removido"],
    answer: 1,
    explanation: "Aberturas em posições favoráveis permitem o fluxo de ar através do ambiente e melhoram o conforto.",
  },
  {
    id: 42,
    category: "Sustentabilidade",
    level: "Médio",
    prompt: "Qual ação reduz desperdícios no canteiro?",
    options: ["Comprar sem quantitativos", "Planejar cortes, armazenar bem e separar resíduos", "Misturar todos os resíduos", "Refazer serviços sem registrar causas"],
    answer: 1,
    explanation: "Planejamento, armazenamento e segregação adequados reduzem perdas de materiais e retrabalho.",
  },
  {
    id: 43,
    category: "Sustentabilidade",
    level: "Técnico",
    prompt: "Resíduos de concreto, argamassa, blocos e tijolos são normalmente associados a qual classe da construção civil?",
    options: ["Classe A", "Classe B exclusivamente", "Classe C exclusivamente", "Resíduo radioativo"],
    answer: 0,
    explanation: "Em geral, esses resíduos minerais são Classe A e podem ser reutilizados ou reciclados como agregados, conforme gestão adequada.",
  },
  {
    id: 44,
    category: "Tecnologia",
    level: "Técnico",
    prompt: "O que melhor descreve BIM?",
    options: ["Somente um desenho em papel", "Processo colaborativo baseado em modelos digitais com informações", "Um tipo de cimento", "Uma máquina de compactação"],
    answer: 1,
    explanation: "BIM integra modelos e informações para apoiar projeto, construção e operação do empreendimento.",
  },
  {
    id: 45,
    category: "Tecnologia",
    level: "Médio",
    prompt: "Softwares CAD são utilizados principalmente para:",
    options: ["Elaborar desenhos técnicos digitais", "Curar concreto", "Compactar o solo", "Transportar materiais"],
    answer: 0,
    explanation: "Ferramentas CAD apoiam a criação, edição e documentação de desenhos técnicos.",
  },
  {
    id: 46,
    category: "Projetos",
    level: "Médio",
    prompt: "A planta baixa representa uma edificação como se fosse:",
    options: ["Vista apenas de baixo", "Cortada horizontalmente e observada de cima", "Fotografada à distância", "Enterrada no solo"],
    answer: 1,
    explanation: "A planta baixa é uma representação obtida por um plano de corte horizontal, vista de cima.",
  },
  {
    id: 47,
    category: "Projetos",
    level: "Médio",
    prompt: "Em desenho técnico, um corte mostra principalmente:",
    options: ["O interior atravessado por um plano imaginário", "Apenas as cores externas", "Somente o nome da obra", "O preço dos materiais"],
    answer: 0,
    explanation: "O corte revela alturas, níveis e elementos internos interceptados ou vistos pelo plano de corte.",
  },
  {
    id: 48,
    category: "Projetos",
    level: "Médio",
    prompt: "A fachada ou elevação representa:",
    options: ["Uma vista externa vertical da edificação", "A resistência do concreto", "A composição do solo", "O cronograma financeiro"],
    answer: 0,
    explanation: "Fachadas são vistas externas verticais que comunicam aberturas, alturas e composição visual.",
  },
  {
    id: 49,
    category: "Topografia",
    level: "Técnico",
    prompt: "Em um levantamento, curvas de nível unem pontos com:",
    options: ["A mesma cota ou altitude", "A mesma cor", "O mesmo proprietário", "A mesma distância da rua"],
    answer: 0,
    explanation: "Curvas de nível representam pontos de igual elevação e ajudam a interpretar o relevo.",
  },
  {
    id: 50,
    category: "Topografia",
    level: "Técnico",
    prompt: "Uma estação total é utilizada para medir principalmente:",
    options: ["Ângulos e distâncias", "Resistência do cimento", "Umidade da tinta", "Vazão do esgoto"],
    answer: 0,
    explanation: "A estação total combina medições angulares e lineares para determinar posições no levantamento.",
  },
  {
    id: 51,
    category: "Matemática",
    level: "Médio",
    prompt: "Qual unidade é adequada para medir a área de um piso?",
    options: ["Metro linear (m)", "Metro quadrado (m²)", "Metro cúbico (m³)", "Quilograma (kg)"],
    answer: 1,
    explanation: "Superfícies como pisos e paredes são normalmente quantificadas em metros quadrados.",
  },
  {
    id: 52,
    category: "Matemática",
    level: "Médio",
    prompt: "Qual unidade é adequada para o volume de concreto de uma laje?",
    options: ["m", "m²", "m³", "km/h"],
    answer: 2,
    explanation: "O concreto ocupa volume e, por isso, é normalmente quantificado em metros cúbicos.",
  },
  {
    id: 53,
    category: "Matemática",
    level: "Médio",
    prompt: "Um piso retangular de 4 m por 3 m possui qual área?",
    options: ["7 m²", "12 m²", "14 m²", "24 m²"],
    answer: 1,
    explanation: "A área do retângulo é base × altura: 4 × 3 = 12 m².",
  },
  {
    id: 54,
    category: "Materiais",
    level: "Técnico",
    prompt: "O ensaio de compressão de corpos de prova de concreto verifica:",
    options: ["A resistência à compressão", "A cor do agregado", "O comprimento da viga", "A inclinação do telhado"],
    answer: 0,
    explanation: "O corpo de prova é carregado até a ruptura para estimar a resistência à compressão do concreto.",
  },
  {
    id: 55,
    category: "Planejamento",
    level: "Médio",
    prompt: "Qual é a função de um cronograma de obra?",
    options: ["Organizar atividades e prazos", "Substituir os projetos", "Eliminar todos os riscos", "Definir a cor do concreto"],
    answer: 0,
    explanation: "O cronograma ordena atividades no tempo e apoia o acompanhamento de prazos e recursos.",
  },
  {
    id: 56,
    category: "Orçamento",
    level: "Médio",
    prompt: "Antes de comprar revestimento, o levantamento de quantitativos ajuda a:",
    options: ["Estimar a quantidade necessária", "Alterar a resistência do solo", "Dispensar medições", "Substituir a mão de obra"],
    answer: 0,
    explanation: "Quantificar os serviços permite estimar materiais, custos e perdas de forma mais controlada.",
  },
  {
    id: 57,
    category: "Planejamento",
    level: "Técnico",
    prompt: "No planejamento, o caminho crítico reúne atividades que:",
    options: ["Não afetam o prazo", "Determinam a duração mínima do projeto", "Podem ser ignoradas", "Custam sempre menos"],
    answer: 1,
    explanation: "Atrasos em atividades críticas tendem a atrasar a conclusão do projeto se não houver recuperação.",
  },
  {
    id: 58,
    category: "Qualidade",
    level: "Médio",
    prompt: "O retrabalho em uma obra normalmente provoca:",
    options: ["Economia garantida", "Perda de tempo, material e dinheiro", "Aumento automático da qualidade", "Eliminação de resíduos"],
    answer: 1,
    explanation: "Refazer serviços consome recursos e costuma prejudicar custo, prazo e produtividade.",
  },
  {
    id: 59,
    category: "Transportes",
    level: "Médio",
    prompt: "A drenagem de uma via é importante porque ajuda a:",
    options: ["Acumular água sobre o pavimento", "Conduzir a água e preservar a via", "Eliminar a sinalização", "Aumentar buracos"],
    answer: 1,
    explanation: "Drenagem adequada reduz acúmulo de água, infiltrações e danos ao pavimento.",
  },
  {
    id: 60,
    category: "Engenharia Civil",
    level: "Médio",
    prompt: "Qual atividade faz parte da atuação da Engenharia Civil?",
    options: ["Projetar e acompanhar edificações e infraestrutura", "Prescrever medicamentos", "Pilotar aeronaves comerciais", "Produzir apenas peças publicitárias"],
    answer: 0,
    explanation: "A Engenharia Civil atua em edificações, estruturas, transportes, saneamento, geotecnia e outras infraestruturas.",
  },
];

const DIFFICULT_LEGACY_IDS = new Set([7, 17, 21, 23, 25, 43, 49, 50, 54, 57]);

const ADDITIONAL_QUESTIONS: Question[] = [
  {
    id: 61,
    category: "Canteiro",
    level: "Fácil",
    prompt: "Para medir o comprimento de uma parede, qual instrumento é mais adequado?",
    options: ["Trena", "Capacete", "Pincel", "Carrinho de mão"],
    answer: 0,
    explanation: "A trena é usada para medir comprimentos e distâncias na obra.",
  },
  {
    id: 62,
    category: "Materiais",
    level: "Fácil",
    prompt: "Qual material é normalmente usado para fabricar tijolos cerâmicos?",
    options: ["Argila", "Vidro", "Borracha", "Alumínio"],
    answer: 0,
    explanation: "Tijolos cerâmicos são produzidos principalmente com argila moldada e queimada.",
  },
  {
    id: 63,
    category: "Segurança",
    level: "Fácil",
    prompt: "Por que uma obra deve ter placas de sinalização?",
    options: ["Para alertar sobre riscos e orientar as pessoas", "Apenas para decorar", "Para esconder ferramentas", "Para substituir os EPIs"],
    answer: 0,
    explanation: "A sinalização comunica riscos, proibições e caminhos seguros.",
  },
  {
    id: 64,
    category: "Sustentabilidade",
    level: "Fácil",
    prompt: "Qual atitude ajuda a economizar água em uma construção?",
    options: ["Consertar vazamentos", "Deixar torneiras abertas", "Lavar calçadas continuamente", "Misturar água limpa com resíduos"],
    answer: 0,
    explanation: "Corrigir vazamentos evita desperdício e reduz o consumo de água.",
  },
  {
    id: 65,
    category: "Projetos",
    level: "Fácil",
    prompt: "Em uma planta de casa, portas e janelas são representadas para indicar:",
    options: ["Suas posições nos ambientes", "A marca do cimento", "O peso da fundação", "O salário da equipe"],
    answer: 0,
    explanation: "A planta mostra a organização dos espaços e a posição das aberturas.",
  },
  {
    id: 66,
    category: "Estruturas",
    level: "Fácil",
    prompt: "Qual parte da casa protege os ambientes da chuva e do sol?",
    options: ["Cobertura", "Rodapé", "Tomada", "Ralo"],
    answer: 0,
    explanation: "A cobertura protege a edificação contra chuva, sol e outras ações do clima.",
  },
  {
    id: 67,
    category: "Instalações",
    level: "Fácil",
    prompt: "Qual instalação leva água até torneiras e chuveiros?",
    options: ["Instalação hidráulica", "Fundação", "Pintura", "Alvenaria"],
    answer: 0,
    explanation: "A instalação hidráulica distribui água aos pontos de consumo.",
  },
  {
    id: 68,
    category: "Matemática",
    level: "Fácil",
    prompt: "Uma parede possui 3 m de largura e 2 m de altura. Qual é sua área?",
    options: ["6 m²", "5 m²", "3 m²", "12 m²"],
    answer: 0,
    explanation: "A área é largura × altura: 3 × 2 = 6 m².",
  },
  {
    id: 69,
    category: "Materiais",
    level: "Fácil",
    prompt: "Qual material transparente é usado com frequência nas janelas?",
    options: ["Vidro", "Concreto", "Areia", "Asfalto"],
    answer: 0,
    explanation: "O vidro permite iluminação e visibilidade através das janelas.",
  },
  {
    id: 70,
    category: "Execução",
    level: "Fácil",
    prompt: "Antes de iniciar uma obra, é importante conhecer:",
    options: ["O projeto e o terreno", "Somente a cor da fachada", "Apenas o nome da rua", "Somente o preço da tinta"],
    answer: 0,
    explanation: "O projeto e as condições do terreno orientam o planejamento e a execução segura.",
  },
  {
    id: 71,
    category: "Conforto",
    level: "Fácil",
    prompt: "Janelas bem posicionadas podem melhorar principalmente:",
    options: ["A iluminação e a ventilação", "O peso do concreto", "A profundidade da fundação", "A resistência da brita"],
    answer: 0,
    explanation: "Aberturas adequadas favorecem luz natural e circulação de ar.",
  },
  {
    id: 72,
    category: "Profissão",
    level: "Fácil",
    prompt: "Quem acompanha projetos e soluções técnicas de edificações e infraestrutura?",
    options: ["Engenheiro civil", "Dentista", "Músico", "Biólogo marinho"],
    answer: 0,
    explanation: "O engenheiro civil atua no planejamento, projeto, execução e manutenção de obras.",
  },
  {
    id: 73,
    category: "Segurança",
    level: "Fácil",
    prompt: "Qual EPI protege os pés no canteiro de obras?",
    options: ["Botina de segurança", "Protetor solar", "Régua", "Prumo"],
    answer: 0,
    explanation: "A botina protege os pés contra impactos, perfurações e outros riscos.",
  },
  {
    id: 74,
    category: "Resíduos",
    level: "Fácil",
    prompt: "Separar resíduos como madeira, metal e plástico facilita:",
    options: ["A reciclagem", "O desperdício", "A contaminação", "O retrabalho"],
    answer: 0,
    explanation: "A separação correta permite encaminhar materiais para reúso ou reciclagem.",
  },
  {
    id: 75,
    category: "Materiais",
    level: "Intermediária",
    prompt: "Uma argamassa muito seca e difícil de espalhar apresenta baixa:",
    options: ["Trabalhabilidade", "Altura", "Transparência", "Voltagem"],
    answer: 0,
    explanation: "Trabalhabilidade é a facilidade de misturar, aplicar e dar acabamento ao material.",
  },
  {
    id: 76,
    category: "Fundações",
    level: "Intermediária",
    prompt: "Por que o tipo de solo influencia a escolha da fundação?",
    options: ["Porque solos suportam cargas de maneiras diferentes", "Porque define a cor das paredes", "Porque muda o número de janelas", "Porque substitui o projeto"],
    answer: 0,
    explanation: "A resistência e o comportamento do solo ajudam a definir uma fundação segura.",
  },
  {
    id: 77,
    category: "Estruturas",
    level: "Intermediária",
    prompt: "Em uma construção comum, qual sequência representa melhor o caminho das cargas?",
    options: ["Laje, viga, pilar, fundação e solo", "Janela, porta, pintura e telha", "Solo, tinta, tomada e laje", "Telha, vidro, argamassa e torneira"],
    answer: 0,
    explanation: "As cargas seguem dos elementos superiores para vigas, pilares, fundações e finalmente o solo.",
  },
  {
    id: 78,
    category: "Instalações",
    level: "Intermediária",
    prompt: "Por que a caixa-d'água costuma ficar em uma posição elevada?",
    options: ["Para favorecer a pressão por gravidade", "Para pesar sobre a pintura", "Para aquecer o concreto", "Para substituir a bomba de esgoto"],
    answer: 0,
    explanation: "A diferença de altura ajuda a movimentar a água e gerar pressão nos pontos de consumo.",
  },
  {
    id: 79,
    category: "Coberturas",
    level: "Intermediária",
    prompt: "Qual é a função principal das calhas em um telhado?",
    options: ["Coletar e conduzir a água da chuva", "Apoiar toda a fundação", "Ventilar a rede de esgoto", "Medir o concreto"],
    answer: 0,
    explanation: "As calhas recebem a água da cobertura e a direcionam para os condutores.",
  },
  {
    id: 80,
    category: "Planejamento",
    level: "Intermediária",
    prompt: "Se a entrega das telhas atrasar, qual atividade pode ser diretamente prejudicada?",
    options: ["A execução da cobertura", "A sondagem já concluída", "A compra do terreno", "A emissão do documento de identidade"],
    answer: 0,
    explanation: "A cobertura depende da disponibilidade das telhas e pode atrasar sem o material.",
  },
  {
    id: 81,
    category: "Projetos",
    level: "Intermediária",
    prompt: "Em escala 1:100, uma linha de 3 cm no desenho representa:",
    options: ["3 m", "30 cm", "30 m", "300 m"],
    answer: 0,
    explanation: "Na escala 1:100, 3 cm representam 300 cm, ou seja, 3 m.",
  },
  {
    id: 82,
    category: "Segurança",
    level: "Intermediária",
    prompt: "Ao perceber um cabo elétrico danificado no canteiro, qual é a melhor conduta?",
    options: ["Isolar a área e comunicar o responsável", "Tocar no cabo para testar", "Cobrir com papel", "Continuar o serviço normalmente"],
    answer: 0,
    explanation: "A área deve ser protegida e o problema encaminhado a uma pessoa qualificada.",
  },
  {
    id: 83,
    category: "Sustentabilidade",
    level: "Intermediária",
    prompt: "Uma vantagem de usar iluminação natural durante o dia é:",
    options: ["Reduzir o consumo de energia elétrica", "Aumentar infiltrações", "Eliminar a ventilação", "Dispensar todas as janelas"],
    answer: 0,
    explanation: "A luz natural pode reduzir a necessidade de iluminação artificial.",
  },
  {
    id: 84,
    category: "Qualidade",
    level: "Intermediária",
    prompt: "Uma parede fora de prumo pode causar principalmente:",
    options: ["Problemas de alinhamento e acabamento", "Aumento da transparência", "Produção de energia", "Redução automática de custos"],
    answer: 0,
    explanation: "A falta de verticalidade prejudica encaixes, revestimentos e a qualidade do serviço.",
  },
  {
    id: 85,
    category: "Pavimentação",
    level: "Intermediária",
    prompt: "Antes de aplicar o revestimento de uma rua, a base deve estar adequadamente:",
    options: ["Preparada e compactada", "Coberta por lixo", "Pintada", "Encharcada sem controle"],
    answer: 0,
    explanation: "Uma base preparada e compactada ajuda a distribuir cargas e aumenta a durabilidade do pavimento.",
  },
  {
    id: 86,
    category: "Impermeabilização",
    level: "Intermediária",
    prompt: "Qual sinal pode indicar falha de impermeabilização?",
    options: ["Manchas de umidade", "Piso nivelado", "Janela aberta", "Lâmpada acesa"],
    answer: 0,
    explanation: "Manchas, bolhas e mofo podem indicar entrada indesejada de água.",
  },
  {
    id: 87,
    category: "Orçamento",
    level: "Intermediária",
    prompt: "Uma parede de 10 m² receberá duas demãos de tinta. Se cada litro cobre 10 m² por demão, sem perdas, serão necessários:",
    options: ["2 litros", "1 litro", "5 litros", "20 litros"],
    answer: 0,
    explanation: "São 20 m² de aplicação no total; com rendimento de 10 m²/L, são necessários 2 L.",
  },
  {
    id: 88,
    category: "Tecnologia",
    level: "Intermediária",
    prompt: "Qual vantagem um modelo digital 3D oferece ao projeto?",
    options: ["Ajuda a visualizar espaços e identificar conflitos", "Elimina a necessidade de medidas", "Constrói sozinho", "Substitui todos os profissionais"],
    answer: 0,
    explanation: "A visualização tridimensional facilita a compreensão e a coordenação do projeto.",
  },
  {
    id: 89,
    category: "Concreto",
    level: "Difícil",
    prompt: "Por que não se deve adicionar água sem controle ao concreto que chegou à obra?",
    options: ["Porque pode alterar a proporção da mistura e reduzir a resistência", "Porque muda apenas a cor", "Porque aumenta sempre a durabilidade", "Porque transforma concreto em aço"],
    answer: 0,
    explanation: "Água extra altera a relação água/cimento e pode aumentar porosidade e reduzir resistência.",
  },
  {
    id: 90,
    category: "Estruturas",
    level: "Difícil",
    prompt: "Por que não é seguro remover um pilar sem análise técnica?",
    options: ["Porque ele pode fazer parte do caminho das cargas", "Porque pilares servem apenas como pintura", "Porque toda parede substitui o pilar", "Porque o piso ficaria mais claro"],
    answer: 0,
    explanation: "A remoção pode interromper a transferência de cargas e comprometer a estabilidade.",
  },
  {
    id: 91,
    category: "Geotecnia",
    level: "Difícil",
    prompt: "Se uma parte do terreno cede mais que outra, a edificação pode sofrer:",
    options: ["Recalque diferencial e fissuras", "Somente mudança de cor", "Aumento da iluminação", "Redução do peso próprio"],
    answer: 0,
    explanation: "Deslocamentos diferentes nas fundações podem gerar deformações e fissuras.",
  },
  {
    id: 92,
    category: "Estruturas",
    level: "Difícil",
    prompt: "Em uma viga apoiada nas extremidades e carregada no centro, a região inferior tende a sofrer principalmente:",
    options: ["Tração", "Compressão pura em toda a seção", "Nenhum esforço", "Flutuação"],
    answer: 0,
    explanation: "Na situação mais comum de flexão positiva, a parte inferior da viga fica tracionada.",
  },
  {
    id: 93,
    category: "Instalações",
    level: "Difícil",
    prompt: "Por que a rede de esgoto precisa de ventilação?",
    options: ["Para equilibrar pressões e ajudar a proteger os fechos hídricos", "Para levar água potável", "Para sustentar a laje", "Para substituir os ralos"],
    answer: 0,
    explanation: "A ventilação reduz variações de pressão e ajuda a evitar a perda da água dos sifões.",
  },
  {
    id: 94,
    category: "Topografia",
    level: "Difícil",
    prompt: "Em um mapa de curvas de nível, linhas muito próximas indicam geralmente:",
    options: ["Terreno mais inclinado", "Terreno totalmente plano", "Ausência de relevo", "Maior largura da rua"],
    answer: 0,
    explanation: "Quanto menor a distância horizontal entre curvas, maior tende a ser a declividade.",
  },
  {
    id: 95,
    category: "Planejamento",
    level: "Difícil",
    prompt: "Duas atividades podem ocorrer ao mesmo tempo quando:",
    options: ["Não existe dependência obrigatória entre elas e há recursos disponíveis", "Uma depende da conclusão da outra", "Nenhuma possui equipe", "O projeto foi cancelado"],
    answer: 0,
    explanation: "Atividades independentes podem ser paralelizadas quando recursos e segurança permitem.",
  },
  {
    id: 96,
    category: "Conforto",
    level: "Difícil",
    prompt: "Em clima quente, qual solução tende a reduzir o aquecimento direto de uma janela?",
    options: ["Brise ou elemento de sombreamento bem dimensionado", "Pintar o vidro de preto", "Fechar toda ventilação", "Retirar a cobertura"],
    answer: 0,
    explanation: "Elementos de sombreamento controlam a incidência solar sem necessariamente bloquear luz e ventilação.",
  },
  {
    id: 97,
    category: "Drenagem",
    level: "Difícil",
    prompt: "Impermeabilizar grandes áreas urbanas sem ampliar a drenagem pode aumentar:",
    options: ["O escoamento superficial e o risco de alagamento", "A infiltração natural", "A absorção pelo solo", "A quantidade de áreas verdes"],
    answer: 0,
    explanation: "Pavimentos impermeáveis reduzem infiltração e fazem mais água escoar rapidamente pela superfície.",
  },
  {
    id: 98,
    category: "Materiais",
    level: "Difícil",
    prompt: "Uma fissura fina causada pela secagem rápida do revestimento está mais relacionada à:",
    options: ["Retração", "Flutuação", "Transparência", "Magnetização"],
    answer: 0,
    explanation: "A perda rápida de água pode provocar retração e o aparecimento de fissuras.",
  },
  {
    id: 99,
    category: "Segurança",
    level: "Difícil",
    prompt: "O cinto para trabalho em altura deve estar conectado a um sistema capaz de:",
    options: ["Restringir ou deter uma queda de forma segura", "Medir paredes", "Transportar concreto", "Substituir o andaime"],
    answer: 0,
    explanation: "O sistema de proteção precisa limitar a exposição ou deter a queda com segurança.",
  },
  {
    id: 100,
    category: "Projetos",
    level: "Difícil",
    prompt: "Quando o projeto arquitetônico e o estrutural mostram elementos ocupando o mesmo espaço, é necessário:",
    options: ["Compatibilizar os projetos antes da execução", "Ignorar o conflito", "Construir os dois no mesmo lugar", "Apagar todas as medidas"],
    answer: 0,
    explanation: "A compatibilização identifica e resolve interferências antes que virem retrabalho na obra.",
  },
  {
    id: 101,
    category: "Orçamento",
    level: "Difícil",
    prompt: "Por que o orçamento deve considerar uma taxa de perdas realista?",
    options: ["Porque cortes, transporte e execução podem consumir material além da medida líquida", "Porque todo material será descartado", "Porque medidas não são necessárias", "Porque isso elimina o controle"],
    answer: 0,
    explanation: "Perdas controladas existem e devem ser estimadas para evitar falta ou excesso de materiais.",
  },
  {
    id: 102,
    category: "Sustentabilidade",
    level: "Difícil",
    prompt: "Uma análise do ciclo de vida de um material considera principalmente:",
    options: ["Impactos desde a obtenção até o descarte ou reciclagem", "Apenas a cor da embalagem", "Somente o preço de compra", "Apenas o transporte final"],
    answer: 0,
    explanation: "O ciclo de vida observa etapas como extração, produção, uso, manutenção e destino final.",
  },
];

const classifiedLegacy: Question[] = LEGACY_QUESTIONS.map((question) => ({
  ...question,
  level: DIFFICULT_LEGACY_IDS.has(question.id)
    ? "Difícil"
    : question.level === "Técnico"
      ? "Intermediária"
      : "Fácil",
}));

export const QUESTIONS: Question[] = adaptQuestionsForPublicSchool([
  ...classifiedLegacy,
  ...ADDITIONAL_QUESTIONS,
  ...EXPANDED_QUESTIONS,
]);
export const PLAYABLE_QUESTIONS = QUESTIONS;

export const QUESTIONS_BY_LEVEL = {
  Fácil: QUESTIONS.filter((question) => question.level === "Fácil"),
  Intermediária: QUESTIONS.filter((question) => question.level === "Intermediária"),
  Difícil: QUESTIONS.filter((question) => question.level === "Difícil"),
} satisfies Record<Question["level"], Question[]>;
